# Equipo 4
**Grupo:** 002, Miércoles

**Integrantes**

+ 1858163, Cárdenas Elizondo, Rebeca
+ 1877340, Leal Cantú, Vanessa 
+ 1847012, Botello Flores, José Ricardo

## Titulo de la base de datos
**a) Nombre con el que se encuentra en la página encontrada**

COVID-19 World  Vaccination Progress

**b) URL de la página**

https://www.kaggle.com/gpreda/covid-world-vaccination-progress

## Descripición de los datos
**a) ¿Qué tipo de datos son?**

Los datos encontrados vienen en forma de tabla y fueron obtenidos de “Our World in Data” que es un repositorio de github para COVID-19.

**b) Descripción de las Columnas**

+ País: referente al país de donde viene la información sobre la vacuna.
+ Fecha: fecha de la entrada de datos. Es importante mencionar que algunas de las fechas son de las vacunas diarias y otras son del total de vacunas. 
+ Total_V: número total de vacunas puestas.
+ Personas_V:  Cada persona dependiendo del esquema de inmunización va a recibir una o dos dosis de vacuna. Hasta cierto punto, va a haber más cantidad de vacunas que de personas.
+ PV_Totalmente: Cantidad de personas que ya recibieron su dosis completa de vacuna (normalmente son 2). 
+ V_Diarias: Cantidad de vacunas diarias a la fecha por país.
+ Nombre_V: Nombre de vacuna usada en el país.

## Justificación del uso de datos
**a) ¿Cuáles fueron las características que les llamó la atención de los datos?**

Los datos presentan información relevante sobre la situación actual de cada país referente al COVID-19. Cada columna presenta información específica sobre la situación de la vacuna en cada país y cuántas personas ya cuentan con al menos una dosis. Estamos interesados en estos datos ya que nos facilita entender ciertos aspectos e incluso nos incita a querer saber más sobre el tema. También nos llamó la atención ya que trabajar con este tipo de datos


**b) ¿Qué beneficio encontramos en trabajar con estos datos?**

El beneficio que encontramos al trabajar con estos datos es que al estar en forma de tabla es muy sencillo por medio de python limpiar datos, en este caso retiramos columnas que no necesitábamos. Una ventaja que encontramos de esta base de datos es que diariamente se actualiza. Hablando del tema en sí, llegamos a la conclusión que se puede apegar a nuestra carrera (Actuaría), incluso podríamos mezclar conocimientos de otras materias con esto.

## Objetivo final
**a) Objetivo principal**

+ Mediante el uso de la base de datos nos interesa saber qué países han tenido un mayor avance con su programa de vacunación.


**b) Objetivos secundarios**

+ Informarnos cuál es la vacuna más utilizada y el por qué. Es decir, si de todas las vacunas alguna tiene mayor eficacia, es más fácil de conseguir e incluso si es más barata. 
+ Saber finalmente la situación de la economía de los países con más vacunas y cómo está su relación con el sector salud. Por ejemplo, nos gustaría saber qué medidas se tomaron desde el principio, su programa de vacunación, etc.

## Preguntas de interés
+ ¿Cuál es el país con un mejor programa de vacunación?
+ ¿Cuál es la vacuna con mayor incidencia a ser usada y por qué?
+ ¿Qué tan afectada se ve la economía de un país al invertir en el sector salud, en este caso la vacuna?
+ ¿El número de vacunas aplicadas  es proporcional a la población del país?

## Programación

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/rbote/Downloads/country_vaccinations.csv")
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
1,Albania,ALB,2021-01-11,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4375,Zimbabwe,ZWE,2021-02-22,1314.0,1314.0,NaN,NaN,328.0,0.01,0.01,NaN,22.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365400469...
4376,Zimbabwe,ZWE,2021-02-23,4041.0,4041.0,NaN,2727.0,808.0,0.03,0.03,NaN,54.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365400469...
4377,Zimbabwe,ZWE,2021-02-24,7872.0,7872.0,NaN,3831.0,1312.0,0.05,0.05,NaN,88.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365400469...
4378,Zimbabwe,ZWE,2021-02-25,11007.0,11007.0,NaN,3135.0,1572.0,0.07,0.07,NaN,106.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365400469...
4379,Zimbabwe,ZWE,2021-02-26,12579.0,12579.0,NaN,1572.0,1750.0,0.08,0.08,NaN,118.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365400469...

Decidimos eliminar las columnas de iso_code, total_vaccination_per_hundred, people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred, daily_vaccinations_per_million, source_name y source_website ya que creemos que no afectarán el análisis que haremos de la base de datos.

In [8]:
#Función para quitar columnas
#http://exponentis.es/como-eliminar-columnas-de-un-dataframe-de-python-pandas
df1 = df.drop(df.columns[[1,6,8,9,10,11,13,14]], axis = 'columns')
df1

,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,vaccines
0,Albania,2021-01-10,0.0,0.0,NaN,NaN,Pfizer/BioNTech
1,Albania,2021-01-11,NaN,NaN,NaN,64.0,Pfizer/BioNTech
2,Albania,2021-01-12,128.0,128.0,NaN,64.0,Pfizer/BioNTech
3,Albania,2021-01-13,188.0,188.0,NaN,63.0,Pfizer/BioNTech
4,Albania,2021-01-14,266.0,266.0,NaN,66.0,Pfizer/BioNTech
...,...,...,...,...,...,...,...
4375,Zimbabwe,2021-02-22,1314.0,1314.0,NaN,328.0,Sinopharm/Beijing
4376,Zimbabwe,2021-02-23,4041.0,4041.0,NaN,808.0,Sinopharm/Beijing
4377,Zimbabwe,2021-02-24,7872.0,7872.0,NaN,1312.0,Sinopharm/Beijing
4378,Zimbabwe,2021-02-25,11007.0,11007.0,NaN,1572.0,Sinopharm/Beijing
4379,Zimbabwe,2021-02-26,12579.0,12579.0,NaN,1750.0,Sinopharm/Beijing

Cambiamos el nombre de las columnas a español para facilitarnos el manejo de las base de datos.

In [10]:
#Función para cambio de nombre
#https://www.iteramos.com/pregunta/7805/-renombrar-las-columnas-en-los-pandas-
df1.rename(columns = {'country':'País'}, inplace=True)
df1.rename(columns = {'date':'Fecha'}, inplace=True)
df1.rename(columns = {'total_vaccinations':'Total_V'}, inplace=True)
df1.rename(columns = {'people_vaccinated':'Personas_V'}, inplace=True)
df1.rename(columns = {'people_fully_vaccinated':'PV_Totalmente'}, inplace=True)
df1.rename(columns = {'daily_vaccinations':'V_Diarias'}, inplace=True)
df1.rename(columns = {'vaccines':'Nombre_V'}, inplace=True)
df1

,País,Fecha,Total_V,Personas_V,PV_Totalmente,V_Diarias,Nombre_V
0,Albania,2021-01-10,0.0,0.0,NaN,NaN,Pfizer/BioNTech
1,Albania,2021-01-11,NaN,NaN,NaN,64.0,Pfizer/BioNTech
2,Albania,2021-01-12,128.0,128.0,NaN,64.0,Pfizer/BioNTech
3,Albania,2021-01-13,188.0,188.0,NaN,63.0,Pfizer/BioNTech
4,Albania,2021-01-14,266.0,266.0,NaN,66.0,Pfizer/BioNTech
...,...,...,...,...,...,...,...
4375,Zimbabwe,2021-02-22,1314.0,1314.0,NaN,328.0,Sinopharm/Beijing
4376,Zimbabwe,2021-02-23,4041.0,4041.0,NaN,808.0,Sinopharm/Beijing
4377,Zimbabwe,2021-02-24,7872.0,7872.0,NaN,1312.0,Sinopharm/Beijing
4378,Zimbabwe,2021-02-25,11007.0,11007.0,NaN,1572.0,Sinopharm/Beijing
4379,Zimbabwe,2021-02-26,12579.0,12579.0,NaN,1750.0,Sinopharm/Beijing



Sumamos la cantidad de datos nulos en cada columna para poder llenarlos con 0 y ver que tan afectados podriamos estar con dicho dato.

In [7]:
df1.isnull().sum()

País                0
Fecha               0
Total_V          1514
Personas_V       1942
PV_Totalmente    2754
V_Diarias         154
Nombre_V            0
dtype: int64

In [11]:
df_0 = df1.fillna(0)
df_0

,País,Fecha,Total_V,Personas_V,PV_Totalmente,V_Diarias,Nombre_V
0,Albania,2021-01-10,0.0,0.0,0.0,0.0,Pfizer/BioNTech
1,Albania,2021-01-11,0.0,0.0,0.0,64.0,Pfizer/BioNTech
2,Albania,2021-01-12,128.0,128.0,0.0,64.0,Pfizer/BioNTech
3,Albania,2021-01-13,188.0,188.0,0.0,63.0,Pfizer/BioNTech
4,Albania,2021-01-14,266.0,266.0,0.0,66.0,Pfizer/BioNTech
...,...,...,...,...,...,...,...
4375,Zimbabwe,2021-02-22,1314.0,1314.0,0.0,328.0,Sinopharm/Beijing
4376,Zimbabwe,2021-02-23,4041.0,4041.0,0.0,808.0,Sinopharm/Beijing
4377,Zimbabwe,2021-02-24,7872.0,7872.0,0.0,1312.0,Sinopharm/Beijing
4378,Zimbabwe,2021-02-25,11007.0,11007.0,0.0,1572.0,Sinopharm/Beijing
4379,Zimbabwe,2021-02-26,12579.0,12579.0,0.0,1750.0,Sinopharm/Beijing

Decidimos cambiar el orden en el que muestra las columnas para facilitarnos el análisis y ver la información de una manera más coherente

In [12]:
#Función cambio de columnas
#https://www.delftstack.com/es/howto/python-pandas/how-to-change-the-order-of-dataframe-columns/
dfn = df_0.reindex(columns = ['País', 'Fecha', 'Nombre_V', 'Personas_V', 'PV_Totalmente', 'Total_V','V_Diarias'])
dfn

,País,Fecha,Nombre_V,Personas_V,PV_Totalmente,Total_V,V_Diarias
0,Albania,2021-01-10,Pfizer/BioNTech,0.0,0.0,0.0,0.0
1,Albania,2021-01-11,Pfizer/BioNTech,0.0,0.0,0.0,64.0
2,Albania,2021-01-12,Pfizer/BioNTech,128.0,0.0,128.0,64.0
3,Albania,2021-01-13,Pfizer/BioNTech,188.0,0.0,188.0,63.0
4,Albania,2021-01-14,Pfizer/BioNTech,266.0,0.0,266.0,66.0
...,...,...,...,...,...,...,...
4375,Zimbabwe,2021-02-22,Sinopharm/Beijing,1314.0,0.0,1314.0,328.0
4376,Zimbabwe,2021-02-23,Sinopharm/Beijing,4041.0,0.0,4041.0,808.0
4377,Zimbabwe,2021-02-24,Sinopharm/Beijing,7872.0,0.0,7872.0,1312.0
4378,Zimbabwe,2021-02-25,Sinopharm/Beijing,11007.0,0.0,11007.0,1572.0
4379,Zimbabwe,2021-02-26,Sinopharm/Beijing,12579.0,0.0,12579.0,1750.0

Averiguamos que tipo de dato maneja cada columna para en el futuro saber con que estaremos trabajando.

In [10]:
df_0.dtypes

País              object
Fecha             object
Total_V          float64
Personas_V       float64
PV_Totalmente    float64
V_Diarias        float64
Nombre_V          object
dtype: object

Enlistamos los paises y vacunas con las que trabajaremos a lo largo del proyecto.

In [4]:
paises = df_0.País.unique()
paises

array(['Albania', 'Algeria', 'Andorra', 'Anguilla', 'Argentina',
       'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Bermuda', 'Bolivia', 'Brazil',
       'Bulgaria', 'Cambodia', 'Canada', 'Cayman Islands', 'Chile',
       'China', 'Colombia', 'Costa Rica', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'England', 'Estonia', 'Faeroe Islands', 'Falkland Islands',
       'Finland', 'France', 'Germany', 'Gibraltar', 'Greece', 'Greenland',
       'Guernsey', 'Guyana', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Japan',
       'Jersey', 'Kazakhstan', 'Kuwait', 'Latvia', 'Lebanon',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Maldives',
       'Malta', 'Mauritius', 'Mexico', 'Monaco', 'Montenegro', 'Morocco',
       'Myanmar', 'Nepal', 'Netherlands', 'New Zealand',
       'Northern Cyprus', 'Northern Ireland', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Poland', 'Portugal',
       'Qatar', 'Romania', 'Russia', 'Saint Helena', 'Saudi Arabia',
       'Scotland', 'Senegal', 'Serbia', 'Seychelles', 'Singapore',
       'Slovakia', 'Slovenia', 'South Africa', 'South Korea', 'Spain',
       'Sri Lanka', 'Sweden', 'Switzerland', 'Trinidad and Tobago',
       'Turkey', 'Turks and Caicos Islands', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Venezuela', 'Wales', 'Zimbabwe'], dtype=object)

In [14]:
vacunas = df_0.Nombre_V.unique()
vacunas

array(['Pfizer/BioNTech', 'Sputnik V', 'Oxford/AstraZeneca',
       'Moderna, Oxford/AstraZeneca, Pfizer/BioNTech',
       'Oxford/AstraZeneca, Sputnik V',
       'Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V',
       'Oxford/AstraZeneca, Sinovac', 'Sinopharm/Beijing',
       'Moderna, Pfizer/BioNTech', 'Pfizer/BioNTech, Sinovac',
       'Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac',
       'Oxford/AstraZeneca, Pfizer/BioNTech',
       'Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V',
       'Covaxin, Oxford/AstraZeneca', 'Sinovac',
       'Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V',
       'Oxford/AstraZeneca, Sinopharm/Beijing',
       'Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V',
       'Johnson&Johnson',
       'Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinopharm/Wuhan, Sputnik V'],
      dtype=object)